//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutum.StaticValues.StringResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutum.StaticValues.StringResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network error occured.
        /// </summary>
        public static string Alert_Error_NetworkException {
            get {
                return ResourceManager.GetString("Alert:Error:NetworkException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Alert_Error_Title {
            get {
                return ResourceManager.GetString("Alert:Error:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error occured.
        /// </summary>
        public static string Alert_Error_UnhandledException {
            get {
                return ResourceManager.GetString("Alert:Error:UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string Alert_No {
            get {
                return ResourceManager.GetString("Alert:No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        public static string Alert_Warning_Title {
            get {
                return ResourceManager.GetString("Alert:Warning:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Alert_Yes {
            get {
                return ResourceManager.GetString("Alert:Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login and/or password.
        /// </summary>
        public static string R_LoginForm_Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("R/LoginForm:Error:InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string R_LoginForm_Login {
            get {
                return ResourceManager.GetString("R/LoginForm:Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string R_LoginForm_Password {
            get {
                return ResourceManager.GetString("R/LoginForm:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string R_LoginForm_Phone {
            get {
                return ResourceManager.GetString("R/LoginForm:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string R_LoginForm_Registration {
            get {
                return ResourceManager.GetString("R/LoginForm:Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string R_LoginForm_Title {
            get {
                return ResourceManager.GetString("R/LoginForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string R_RegistrationForm_Name {
            get {
                return ResourceManager.GetString("R/RegistrationForm:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string R_RegistrationForm_Password {
            get {
                return ResourceManager.GetString("R/RegistrationForm:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string R_RegistrationForm_Phone {
            get {
                return ResourceManager.GetString("R/RegistrationForm:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy policy.
        /// </summary>
        public static string R_RegistrationForm_PrivacyPolicy {
            get {
                return ResourceManager.GetString("R/RegistrationForm:PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        public static string R_RegistrationForm_RepeatPassword {
            get {
                return ResourceManager.GetString("R/RegistrationForm:RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string R_RegistrationForm_Submit {
            get {
                return ResourceManager.GetString("R/RegistrationForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string R_RegistrationForm_Title {
            get {
                return ResourceManager.GetString("R/RegistrationForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS code.
        /// </summary>
        public static string R_RegistratonFinalizeForm_SmsCode {
            get {
                return ResourceManager.GetString("R/RegistratonFinalizeForm:SmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish registration.
        /// </summary>
        public static string R_RegistratonFinalizeForm_Submit {
            get {
                return ResourceManager.GetString("R/RegistratonFinalizeForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finishing registration.
        /// </summary>
        public static string R_RegistratonFinalizeForm_Title {
            get {
                return ResourceManager.GetString("R/RegistratonFinalizeForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Course.
        /// </summary>
        public static string Shell_Course {
            get {
                return ResourceManager.GetString("Shell:Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string Shell_Main {
            get {
                return ResourceManager.GetString("Shell:Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Shell_Profile {
            get {
                return ResourceManager.GetString("Shell:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free.
        /// </summary>
        public static string U_C_CourseForm_Free {
            get {
                return ResourceManager.GetString("U/C/CourseForm:Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Premium.
        /// </summary>
        public static string U_C_CourseForm_Premium {
            get {
                return ResourceManager.GetString("U/C/CourseForm:Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, buy premium account.
        /// </summary>
        public static string U_C_CourseForm_Warning_Premium {
            get {
                return ResourceManager.GetString("U/C/CourseForm:Warning:Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy.
        /// </summary>
        public static string U_M_MainForm_Buy {
            get {
                return ResourceManager.GetString("U/M/MainForm:Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The best agility and abs training tools You need only 2 sq.m on the floor and gravity.
        /// </summary>
        public static string U_M_MainForm_DescriptionLabel {
            get {
                return ResourceManager.GetString("U/M/MainForm:DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tutum Fitness.
        /// </summary>
        public static string U_M_MainForm_TitleLabel {
            get {
                return ResourceManager.GetString("U/M/MainForm:TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New phone number.
        /// </summary>
        public static string U_P_CN_NumberForm_Phone {
            get {
                return ResourceManager.GetString("U/P/CN/NumberForm:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send validation SMS.
        /// </summary>
        public static string U_P_CN_NumberForm_Submit {
            get {
                return ResourceManager.GetString("U/P/CN/NumberForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing phone number.
        /// </summary>
        public static string U_P_CN_NumberForm_Title {
            get {
                return ResourceManager.GetString("U/P/CN/NumberForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS code.
        /// </summary>
        public static string U_P_CN_NumberSmsForm_Code {
            get {
                return ResourceManager.GetString("U/P/CN/NumberSmsForm:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change phone number.
        /// </summary>
        public static string U_P_CN_NumberSmsForm_Submit {
            get {
                return ResourceManager.GetString("U/P/CN/NumberSmsForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing phone number.
        /// </summary>
        public static string U_P_CN_NumberSmsForm_Title {
            get {
                return ResourceManager.GetString("U/P/CN/NumberSmsForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password.
        /// </summary>
        public static string U_P_CP_PasswordForm_Password {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordForm:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password repeated.
        /// </summary>
        public static string U_P_CP_PasswordForm_PasswordRepeated {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordForm:PasswordRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send SMS.
        /// </summary>
        public static string U_P_CP_PasswordForm_Submit {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing Password.
        /// </summary>
        public static string U_P_CP_PasswordForm_Title {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS code.
        /// </summary>
        public static string U_P_CP_PasswordSMSForm_Code {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordSMSForm:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        public static string U_P_CP_PasswordSMSForm_Submit {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordSMSForm:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing Password.
        /// </summary>
        public static string U_P_CP_PasswordSMSForm_Title {
            get {
                return ResourceManager.GetString("U/P/CP/PasswordSMSForm:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string U_P_ProfileForm_LanguageLabel {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select language.
        /// </summary>
        public static string U_P_ProfileForm_LanguagePicker {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:LanguagePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string U_P_ProfileForm_Logout {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string U_P_ProfileForm_NameLabel {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string U_P_ProfileForm_NamePlaceholder {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Password.
        /// </summary>
        public static string U_P_ProfileForm_Password {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Phone Number.
        /// </summary>
        public static string U_P_ProfileForm_PhoneButton {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:PhoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        public static string U_P_ProfileForm_PhoneLabel {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string U_P_ProfileForm_PhonePlaceholder {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to change a language to {0}? Restart is required.
        /// </summary>
        public static string U_P_ProfileForm_Warning_Language {
            get {
                return ResourceManager.GetString("U/P/ProfileForm:Warning:Language", resourceCulture);
            }
        }
    }
}
